name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [aws_california, aws_ohio, aws_paris, aws_tokyo, aws_dublin, aws_brazil]

    env:
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:

    - name: Debug Print Environment Variables
      run: |
        echo "$EC2_USER"
        echo "${{ env.EC2_USER }}"
        echo "$EC2_KEY"
        echo "${{ secrets.EC2_KEY }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Create symbolic link
      run: |
        cd client/src
        ln -s ../../shared ./

    - name: DEBUG-List directory contents after symbolic link
      run: |
        node --version
        npm -version
        pwd

    - name: Debug List directory contents after symbolic link
      run: |
        pwd
        ls -lha client/src/
        ls -lha client/src/shared

    - name: Debug Print config-overrides.js
      run: cat client/config-overrides.js

    - name: Debug Print tsconfig.json
      run: cat client/tsconfig.json

    - name: Install dependencies and build client
      run: |
        cd client
        npm install
        CI=false npm run build2

    - name: Install server dependencies
      run: |
        cd server
        npm install

    - name: Set EC2_HOST for aws_california
      if: matrix.server == 'aws_california'
      run: echo "EC2_HOST=${{ secrets.EC2_HOST_AWS_CALIFORNIA }}" >> $GITHUB_ENV

    - name: Set EC2_HOST for aws_ohio
      if: matrix.server == 'aws_ohio'
      run: echo "EC2_HOST=${{ secrets.EC2_HOST_OHIO }}" >> $GITHUB_ENV

    - name: Set EC2_HOST for aws_paris
      if: matrix.server == 'aws_paris'
      run: echo "EC2_HOST=${{ secrets.EC2_HOST_PARIS }}" >> $GITHUB_ENV

    - name: Set EC2_HOST for aws_tokyo
      if: matrix.server == 'aws_tokyo'
      run: echo "EC2_HOST=${{ secrets.EC2_HOST_TOKYO }}" >> $GITHUB_ENV

    - name: Set EC2_HOST for aws_dublin
      if: matrix.server == 'aws_dublin'
      run: echo "EC2_HOST=${{ secrets.EC2_HOST_DUBLIN }}" >> $GITHUB_ENV

    - name: Set EC2_HOST for aws_brazil
      if: matrix.server == 'aws_brazil'
      run: echo "EC2_HOST=${{ secrets.EC2_HOST_BRAZIL }}" >> $GITHUB_ENV

    - name: Debug Print Environment Variables
      run: |
        echo "$EC2_USER"
        echo "$EC2_HOST"
        echo "${{ env.EC2_USER }}"
        echo "${{ env.EC2_HOST }}"

    - name: Deploy to EC2
      run: |
        echo "${EC2_KEY}" > key.pem
        chmod 600 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem -r . "${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/var/www/rosecrest"

    - name: SSH and restart server
      run: |
        echo "${EC2_KEY}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem "${{env.EC2_USER}}@${{env.EC2_HOST}}" << 'EOF'
          cd /var/www/rosecrest
          sudo systemctl restart nginx
          pm2 restart server